### ISSUE TITLE
Embedding headway widget closes down about.html

### ISSUE THREAD

**Issue by githubfan** [githubfan/githubfan.github.io#5]
@locness3 , Can you help?

**Comment by moeenio** [comment]
I can't find the headway code in about.html on `master`.

**Comment by githubfan** [comment]
I'll send it.

**Comment by githubfan** [comment]
<script>
  // @see https://docs.headwayapp.co/widget for more configuration options.
  var HW_config = {
    selector: ".CHANGE_THIS", // CSS selector where to inject the badge
    account:  "x8XQBx"
  }
</script>
<script async src="https://cdn.headwayapp.co/widget.js"></script>
That's it. Please create a PR and I'll approve it.

**Comment by moeenio** [comment]
You should put that code in about.html, and replace`.CHANGE_THIS` with the CSS selector of the element you want to use to toggle the popup.

**Comment by moeenio** [comment]
You should put that code in about.html, and replace `.CHANGE_THIS` with the CSS selector of the element you want to use to toggle the popup. @githubfan

**Comment by githubfan** [comment]
Ok
